swagger: '2.0'
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
host: CLOUD_RUN_HOSTNAME
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://cloud-resume-challenge-ouvnbq3x2q-de.a.run.app
  protocol: h2
paths:
  /hello:
    get:
      summary: Increment visitor count
      operationId: increment
      responses:
        '200':
          description: A successful response
          schema:
            type: string