swagger: '2.0'
info:
  title: api-gateway
  description: API Gateway
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /increment:
    get:
      summary: Increment visitor count
      operationId: increment
      x-google-backend:
        address: https://cloud-resume-challenge-ouvnbq3x2q-de.a.run.app # You need to change this!
      responses:
        '200':
          description: OK