name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out 
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: . ./init.sh ${{ secrets.GCP_PROJECT_ID }} ${{ secrets.GCP_REGION }} ${{ secrets.GCP_KEY }}
        