name: GitHub Actions Demo
on: 
  push:
  repository_dispatch:
    types: [opened, deleted]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out 
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Edit .firebaserc file
        working-directory: ./firebase
        run: |
          echo $PWD
          find ./.firebaserc -type f -exec sed -i 's/<GCP_PROJECT_ID>/${{ secrets.GCP_PROJECT_ID }}/g' {} \;

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy --only firestore:rules
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_ENCODED }}
        working-directory: ./firebase

      - name: Use gcloud CLI
        run: | 
          mkdir FE
          git clone ${{ secrets.FE_GITHUB_URL }} FE
          mkdir BE
          git clone ${{ secrets.BE_GITHUB_URL }} BE
          chmod +x ./init.sh
          ls
          ./init.sh ${{ secrets.GCP_REGION }} ${{ secrets.GCP_PROJECT_ID }}
        